apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application1
  namespace: argocd111
spec:
  project: default

  source:
    repoURL: https://github.com/VanMyan/argocd-myfirstapp.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp111

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true